### ISSUE TITLE
Show year in scrollable timeline

### ISSUE THREAD

**Issue by anseljh** [L4GG/timeline#16]
When scrolling through the early part of the timeline, it's very confusing because the year isn't displayed.

![image](https://cloud.githubusercontent.com/assets/2075772/25737681/01d479b8-312e-11e7-8bfb-e734c28ebdce.png)

**Comment by jlegrone** [comment]
I'm closing this for now -- I think this will be alleviated by having a wider initial zoom and perhaps custom date range controls in a toolbar at the top.
