### ISSUE TITLE
Need consistency in Source's media names

### ISSUE THREAD

**Issue by engerm** [L4GG/timeline#36]
The names of the media's name need to be consistent.

Examples:
- http://timeline.lawyersforgoodgovernment.org/#event-1996-trump-applies-for-trademark-in-russia
-- NY Times
- http://timeline.lawyersforgoodgovernment.org/#event-1992-trump’s-fourth-bankruptcy
-- New York Times

I have not checked all of the events, but I started noticing the inconsistency of the Source's names

#### Event Title
n/a

#### Event Date
n/a

#### Event Description
n/a

#### Source Link
n/a

#### Source Attribution
n/a

#### Blockquote
n/a

#### Media Image <sup>(if no quote/url)</sup>
n/a

#### Media URL <sup>(if no quote/image)</sup>
n/a

#### Media Attribution
n/a

#### Media Caption
n/a

**Comment by sgeofrank** [comment]
@engerm Fixed with latest push from the content team. Thanks!
