### ISSUE TITLE
slow loading time in browser when nexting events

### ISSUE THREAD

**Issue by engerm** [L4GG/timeline#43]
Since the site is heavy JS, the browser is doing a lot of the work. The performance and response when interacting with the site is slow.

The site should be more responsive in the browser: nexting events; scrolling through the timeline, etc...

Example:
http://timeline.lawyersforgoodgovernment.org/#event-2016-flynn-endorses-trump
(next back and forth; scroll through timeline)

Tested this in Chrome and Firefox on a Mac.

**Comment by sgeofrank** [comment]
@engerm can you retest back and forth, @jlegrone pushed improvements

**Comment by engerm** [comment]
Looks good to me now.

**Comment by jlegrone** [comment]
Thanks for confirming @engerm -- closing this.  #61 will enable some further improvements.
