### ISSUE TITLE
Expose events as a json endpoint, optionally without description markup

### ISSUE THREAD

**Issue by jlegrone** [L4GG/timeline#45]

**Comment by thekevinscott** [comment]
I'm thinking the API schema would basically match the routing structure of the current site (only `GET` actions):

```
GET / - ???
GET /years - return an array of all years for which we have data
GET /years/{year} - returns an array of all events in that year for which we have data
GET /years/{year}/{event_slug} - returns information on a particular event, including date, title, description, image, tags, and any other information we have.
```

Some assumptions:

* For the event's content, I'm thinking we take a folder's contents - stuff like `tags.csv`, `start-date.txt` - and use the filename (sans extension) as the object key, and the file's contents as the value. This way, we can add / remove new keys on the fly. Feedback?
* Should events live at `/events/{event_slug}`? Maybe we can lose the year stuff there.
* Do we want an `/events` endpoint that lists all events? If so we'd probably want to look at things like paging / limiting etc.

Side note, moving events to an API endpoint could allow the frontend to query the API directly, which would cut down on initial bundle size. Win / win!

**Comment by thekevinscott** [comment]
Currently, the `events` folder lives in `/src` and is copied as part of the Webpack bundle. To move to an API we'll need this in a consumable format via Node.

One option is to copy the events folder as part of the production bundle (aka, copy it to `/dist` or move it one level up) and read in the directory / file structures using Node.

A second option would be to use Webpack to generate a separate output file, like `events.bundle.js`, which would contain all the data, and then read that into memory in `server.js`.

The first option seems much better to me. However, I want to be cognizant of not doing anything that could break the frontend until it gets updated to query this future API.

**Comment by jlegrone** [comment]
@thekevinscott I like option no. 2 as a quick and dirty solution; there's a lot going on in webpack right now that would be a bit of a pain to replicate in node.  Once we are able to read event data into memory we can do whatever we want, so that's a great starting point for building an api.

I also would be happy moving the events directory to the root if you feel that makes sense.  Just separating all the event data from the main js bundle is a great starting point.

**Comment by thekevinscott** [comment]
Ah shoot, just saw your comment! I just wrapped up a very basic API but we can put a hold on it. I ended up moving events into a content folder. I'll PR what I've got just so it's up there but no need to move on it any time soon.

**Comment by anseljh** [comment]
I like the idea of building a JSON file from the event data we have now. That could be generated by an npm script, i.e., `npm json`. This is nice because people can then use whatever tools they want on the underlying data. Journalists are going to want the bulk data to remix, etc., and we should make that easy.

Eventually, the JSON could also become the canonical data source, and the `events` folder could go away. Is there any reason not to have the JSON just _be_ the API? (I think that's what @thekevinscott was saying on his second option.)
